# Generated by Django 6.0.1 on 2026-03-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverypartner',
            old_name='is_available',
            new_name='availability',
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_documents/'),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_profiles/'),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
