# Generated by Django 6.0.1 on 2026-03-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_rename_is_available_deliverypartner_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
