# Generated by Django 6.0.1 on 2026-02-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_razorpay_order_id_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('upi', 'UPI'), ('razorpay', 'Razorpay'), ('card', 'Card'), ('netbanking', 'Net Banking')], max_length=20),
        ),
    ]
