# Generated by Django 6.0.1 on 2026-02-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
