# Generated by Django 6.0 on 2025-12-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productvariant_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='upi_app',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking')], default='upi', max_length=20),
            preserve_default=False,
        ),
    ]
