# Generated by Django 6.0.1 on 2026-03-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_productvariant_qr_code_order_delivery_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_response',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
