# Generated by Django 6.0.1 on 2026-03-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_proof/'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
