# Generated by Django 6.0 on 2025-12-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_return_comment_order_return_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_status',
            field=models.CharField(choices=[('none', 'None'), ('requested', 'Requested'), ('pickup_scheduled', 'Pickup Scheduled'), ('picked', 'Picked'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed')], default='none', max_length=30),
        ),
    ]
