# Generated by Django 6.0.1 on 2026-04-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
