# Generated by Django 6.0.1 on 2026-02-15 17:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('total_quantity', models.IntegerField(default=0)),
                ('available_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('Returned', 'Returned'), ('Damaged', 'Damaged')], max_length=20)),
                ('damage_description', models.TextField(blank=True, null=True)),
                ('action_status', models.CharField(choices=[('Pending', 'Pending'), ('Repairing', 'Repairing'), ('Repaired', 'Repaired'), ('Replaced', 'Replaced'), ('Discarded', 'Discarded')], default='Pending', max_length=20)),
                ('date_reported', models.DateTimeField(default=django.utils.timezone.now)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.equipment')),
            ],
        ),
    ]
