# Generated by Django 6.0.1 on 2026-02-15 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_payment_method'),
        ('warehouse', '0002_equipment_returndamage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returndamage',
            name='equipment',
        ),
        migrations.AddField(
            model_name='returndamage',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returndamage',
            name='date_reported',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
