# Generated by Django 6.0.1 on 2026-02-16 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_rack_section_warehouse_productlocation_rack_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
