# Generated by Django 6.0.1 on 2026-02-16 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_warehouse_capacity_warehouse_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
