# Generated by Django 6.0.1 on 2026-02-18 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_payment_method'),
        ('warehouse', '0007_stocktransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockout',
            name='product',
        ),
        migrations.AddField(
            model_name='stockout',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productvariant'),
        ),
    ]
