# Generated by Django 6.0.1 on 2026-02-19 18:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_payment_method'),
        ('warehouse', '0008_remove_stockout_product_stockout_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('transferred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='warehouse.rack')),
                ('to_rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='warehouse.rack')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productvariant')),
            ],
        ),
    ]
